apiVersion: v1
kind: ServiceAccount
metadata:
  name: classmate-api-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: classmate-api-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "patch", "delete"]