# Kubernetes Deployment Files for the Springboot BE
# To apply config file: kubectl apply -f .k8s/classmate-api.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: classmate-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: classmate-api
  template:
    metadata:
      labels:
        app: classmate-api
    spec:
      containers:
        - name: classmate-api
          image: ghcr.io/sccapstone/group16/classmate-api:latest
          ports:
            - containerPort: 1616
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: classmate-secrets
                  key: MONGO_URI
            - name: MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: classmate-secrets
                  key: MONGO_DATABASE
            - name: MAIL_SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: classmate-secrets
                  key: MAIL_SMTP_HOST
            - name: MAIL_SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: classmate-secrets
                  key: MAIL_SMTP_PORT
            - name: MAIL_SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: classmate-secrets
                  key: MAIL_SMTP_USERNAME
            - name: MAIL_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: classmate-secrets
                  key: MAIL_SMTP_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: classmate-api
spec:
  selector:
    app: classmate-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1616
      nodePort: 30016
  type: ClusterIP