theme: jekyll-theme-slate
title: "classMA+E"
description: >
 classMA+E is a personal assignment-planning app that will work with the Blackboard API to retrieve a student's active assignments, quizzes, announcements, and more.