---
theme: jekyll-theme-slate
title: "classMA+E"
description: This site will describe classMA+E and how to use its features.
---

<div class="centered-text">
  <h1>{{ page.title }}</h1>
  <p>{{ page.description }}</p>
</div>
