apiVersion: v1
kind: Service
metadata:
  name: classmate-api
spec:
  selector:
    app: classmate-api
  ports:
    - protocol: TCP
      port: 1616   # External port (incoming traffic)
      targetPort: 1616  # Port your pods are listening on
      nodePort: 30016  # NodePort (range 30000-32767)
  type: NodePort # LoadBalancer