name: BE Docker Image

on:
  push:
    branches: 
      - main
      - release/*
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Set up JDK 17
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: 'temurin'
      #     java-version: '17'

      - name: Set up environment variables
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
          echo "MONGO_DATABASE=${{ secrets.MONGO_DATABASE }}" >> $GITHUB_ENV
          echo "MAIL_SMTP_HOST=${{ secrets.MAIL_SMTP_HOST }}" >> $GITHUB_ENV
          echo "MAIL_SMTP_PORT=${{ secrets.MAIL_SMTP_PORT }}" >> $GITHUB_ENV
          echo "MAIL_SMTP_USERNAME=${{ secrets.MAIL_SMTP_USERNAME }}" >> $GITHUB_ENV
          echo "MAIL_SMTP_PASSWORD=${{ secrets.MAIL_SMTP_PASSWORD }}" >> $GITHUB_ENV

      - name: Change Directory
        run: cd src/be

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build \
            --build-arg JAR_FILE=target/be-0.2.jar \
            --build-arg MONGO_URI=${{ secrets.MONGO_URI }} \
            --build-arg MONGO_DATABASE=${{ secrets.MONGO_DATABASE }} \
            --build-arg MAIL_SMTP_HOST=${{ secrets.MAIL_SMTP_HOST }} \
            --build-arg MAIL_SMTP_PORT=${{ secrets.MAIL_SMTP_PORT }} \
            --build-arg MAIL_SMTP_USERNAME=${{ secrets.MAIL_SMTP_USERNAME }} \
            --build-arg MAIL_SMTP_PASSWORD=${{ secrets.MAIL_SMTP_PASSWORD }} \
            -t ghcr.io/$REPO_NAME/classmate-api:latest \
            -f src/be/Dockerfile src/be

      - name: Push Docker image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$REPO_NAME/classmate-api:latest