name: Spring Boot Tests

on: 
    push:
        branches:
            - main
            - release/*
    pull_request:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-22.04

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '17'

        - name: Change Directory
          run: cd src/be

        - name: Cache Maven packages
          uses: actions/cache@v3
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
                ${{ runner.os }}-maven-
                maven-

        - name: Install dependencies
          run: mvn install -DskipTests

        - name: Run tests
          run: mvn test